name: Node CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.17.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.17.0
    - run: yarn install
    - name: Lint
      run: |
        yarn run tslinter
        yarn run sasslinter
      env:
        CI: true
