name: Node CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - uses: actions/checkout@v1
    - name: Use Node.js "${{ steps.nvm.outputs.NVMRC }}"
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - run: yarn install
    - name: Lint
      run: |
        yarn run tslinter
        yarn run sasslinter
      env:
        CI: true
